#!/bin/bash

OS=$(uname -s)

cd "$HOME"

echo "initializing submodules..."
yadm submodule update --init --recursive

if [ "$OS" = "Darwin" ]; then
  echo "installing darwin-specific bits..."
  source ".config/yadm/bootstrap.macos"
fi

if [ $(basename "$SHELL") != "fish" ]; then
  echo "setting fish as default shell..."
  chsh -s "$(which fish)"
fi

if command -v nvim >/dev/null 2>&1; then
  echo "bootstrapping nvim plugins..."
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

if [ ! -d "$HOME/.local/share/terminfo" ]; then
  echo "updating terminfo database...."
  curl -sLO http://invisible-island.net/datafiles/current/terminfo.src.gz
  gunzip terminfo.src.gz
  tic -xe tmux-256color,alacritty-direct -o "$HOME/.local/share/terminfo" terminfo.src
  rm terminfo.src
fi

echo "done! you should restart your terminal"
